version: "3"
services:
  influxdb:
    image: influxdb:2.7-alpine
    hostname: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - ${PWD}/etc/influxdb.conf:/etc/influxdb2/influxdb.conf
      - ${INFLUXDB_PATH}:/var/lib/influxdb2
    ports:
      - 8086:8086
  telegraf:
    image: telegraf:1.27-alpine
    hostname: telegraf
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      TELEGRAF_USERNAME: ${TELEGRAF_USERNAME}
      TELEGRAF_PASSWORD: ${TELEGRAF_PASSWORD}
    volumes:
      - ${PWD}/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:2
    hostname: mosquitto
    restart: always
    volumes:
      - ${PWD}/etc/mosquitto:/mosquitto/config
    ports:
      - 1883:1883
    entrypoint: >
      sh -c "/mosquitto/config/mqtt_passwd -b "${TELEGRAF_USERNAME}" "${TELEGRAF_PASSWORD}";
             /docker-entrypoint.sh /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"
